### ISSUE TITLE
"Unable to load file" with a relative path

### ISSUE THREAD

**Issue by remss** [electron/rcedit#48] opened 2017-06-21 13:30 UTC
A simple directory structure

```
root
+-- a
¦   +-- rcedit.exe
+-- b
¦   +-- foo.exe
```

Now with CWD = root, the command fails

```
a\rcedit.exe b\foo.exe
Fatal error: Unable to load file
# exit status = 1
```

But if CWD = root\a, the command success

```
rcedit.exe ..\b\foo.exe
# exit status = 0
```

rcedit version = v0.1.0

**Comment by zcbenz** [comment] 2017-09-13 06:57
I'm unable to reproduce, you may try the latest binaries.

**Comment by remss** [comment] 2017-09-13 10:06
I see only release 0.1.0 at https://github.com/electron/rcedit/releases

**Comment by zcbenz** [comment] 2017-09-13 12:32
I forgot we even have a releases page, you can find prebuilt binaries in the CI jobs:
https://ci.appveyor.com/project/electron-bot/rcedit/build/1.0.29

**Comment by remss** [comment] 2017-09-13 14:08
I confirm that the issue persists in 1.0.29 release (tested all VS15/17 win32/x64)

**Comment by zcbenz** [comment] 2017-09-14 00:35
Hmm I have no idea what's happening on your machine, the node-rcedit module just works fine, which calls rcedit from arbitrary cwd on arbitrary files.

**Comment by remss** [comment] 2017-09-15 09:07
The problem concerns the rcedit.exe binary, not the npm module. Can you please try the above scenario ?

**Comment by zcbenz** [comment] 2017-09-16 00:57
I did try your scenario and it worked. The node-rcedit module works by executing the rcredit.exe on arbitrary file under arbitrary cwd, which technically does not have any difference with executing rcredit.exe under shell.

So it seems to me that the problem is on your side, unless you can provide a test case to prove it is a bug of rcedit.

**Comment by remss** [comment] 2017-09-19 09:53
Its seems that something goes wrong on my PC because I tested on two others windows10/x64 PCs and the `a\rcedit.exe b\foo.exe` works fine...
Any clue on this ?

**Comment by zcbenz** [comment] 2017-09-20 04:07
No I have never seen a problem like this.

**Comment by remss** [comment] 2017-09-20 14:11
I got some new on this... it works with prefix `.\` !

So `a\rcedit.exe b\foo.exe` fails.
And `a\rcedit.exe .\b\foo.exe` succeeds.
And `a\rcedit.exe C:\my\full\path\b\foo.exe` succeeds.

The problem is in `rescle.cc` line 381, LoadLibraryExW run with error code 2 = ERROR_FILE_NOT_FOUND (from GetLastError).
LoadLibraryEx uses the [dll search order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx)  that will use CWD only if SafeDllSearchMode=Off
I had SafeDllSearchMode=On on my computer so I tried to set to true but the lookup still fails, don't know why...
Anyway the lookup seems depends on the host configuration so resolving the filename to an absolute path just before calling LoadLibraryExW() may to be a good solution to fix this issue ?

**Comment by zcbenz** [comment] 2017-09-25 02:42
@remss Excellent finding, I think resolving the filename is a perfect solution.

**Closed** 2017-09-26 05:54 UTC
Labels: question

**Comment by remss** [comment] 2017-09-26 08:02
Thank you !

**Comment by vladislav-tkach** [comment] 2022-03-25 11:48
@zcbenz not sure it is the same issue but I am getting the same message "Unable to load file" and the issue seems to be at the same place - the LoadLibraryExW call in ResourceUpdater::Load function. The last error id is 193. It has something to do with bitness of the machine and the project as I understand.

Here is what I have found:
https://stackoverflow.com/questions/22683601/loadlibrary-always-return-null

Unfortunately, my knowledge is insufficient for further investigation. I hope it helps improving the tool!
